name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create scripts folder (just in case)
        run: mkdir -p scripts

      - name: Run build script with secret
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: node scripts/generate.js

      - name: Upload build folder
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: ./public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
